# Generated by Django 3.1.7 on 2021-05-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_clone_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videos',
            old_name='name',
            new_name='Comments',
        ),
    ]
